---
name: Implementation tests

on:
  workflow_call:
    inputs:
      implementation:
        required: true
        type: string
      platform:
        required: true
        type: string
      python-version:
        required: true
        type: string
      zarr-python:
        required: true
        type: string

jobs:

  test_implementations:
    name: ${{ inputs.implementation }}-${{ inputs.platform }}-py${{ inputs.python-version }}-${{ inputs.zarr-python }}
    runs-on: ${{ inputs.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles( format('{0}/{1}/{2}', 'implementations/', inputs.implementation, '/environment.yml') ) }}

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          channel-priority: true
          environment-file: implementations/${{ inputs.implementation }}/environment.yml
          mamba-version: "*"
          python-version: ${{ inputs.python-version }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Rename conda environment
        shell: bash
        run: |
          conda rename --name test ZI_${{ inputs.implementation }}

      - name: Install zarr dev (optional)
        shell: bash -l {0}
        if: ${{ inputs.config.zarr-python == 'pre' }}
        run: |
          python -m pip install git+https://github.com/zarr-developers/zarr-python.git

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        shell: bash -l {0}
        run: make implementations/${{ inputs.implementation }}
