---
name: Implementation tests

on:
  workflow_call:
  
env:
  CACHE_NUMBER: 0

jobs:

  test_implementations:
    name: read-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download previous artifacts
        uses: actions/download-artifact@v3
        with:
          path: data
        
      # - name: Move build cache
      #   run: |
      #     cp -r /tmp/artifacts/*.zr data/
      #     cp -r /tmp/artifacts/*.zr3 data/
      #     cp -r /tmp/artifacts/*.n5 data/
      #   shell: bash
      
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          channel-priority: true
          mamba-version: "*"
          python-version: ${{ inputs.python-version }}
          activate-environment: ZI_${{ inputs.implementation }}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Cache conda env - Rarr
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs/ZI_Rarr
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles( 'implementations/Rarr/environment.yml') }}
  
        
      - name: Cache conda env - js
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs/ZI_Rarr
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles( 'implementations/js/environment.yml') }}

      - name: ls 2
        run: |
          pytest test/test_read_all.py -v
